path: C:/Users/user/Desktop/code/vsc git/Diabetic-Retinopathy/dataset/IDRiD/A. Segmentation/IDRiD_yolo
train: C:/Users/user/Desktop/code/vsc git/Diabetic-Retinopathy/runs/kfold_experiments/KFold_Run_20260126_104539/configs/train_f2.txt
val: C:/Users/user/Desktop/code/vsc git/Diabetic-Retinopathy/runs/kfold_experiments/KFold_Run_20260126_104539/configs/val_f2.txt
nc: 5
names:
  0: MA
  1: HE
  2: EX
  3: SE
  4: OD
